/**
 * Sprite-sheet atlas for the canvas renderer. Presentation-side (touches the
 * DOM Image API), kept out of the pure simulation like renderer.ts.
 *
 * Sheets are horizontal strips of equally-sized frames generated by
 * `tools/generate-sprites.mjs` into public/assets/sprites/. The atlas is
 * optional everywhere: until it has loaded (or if loading fails) the renderer
 * falls back to its procedural shapes, so nothing ever blocks on an image.
 */

export const SHEET_SPECS = {
  'diver-freefall': { fw: 16, fh: 16, frames: 5 },
  'diver-deploy': { fw: 16, fh: 24, frames: 6 },
  canopy: { fw: 32, fh: 32, frames: 4 },
  'diver-land': { fw: 16, fh: 16, frames: 6 },
  'diver-crash': { fw: 16, fh: 16, frames: 4 },
  plane: { fw: 48, fh: 32, frames: 3 },
  terrain: { fw: 16, fh: 16, frames: 10 },
} as const;

export type SheetName = keyof typeof SHEET_SPECS;

/** Frame indices inside terrain.png. */
export enum TerrainSprite {
  TreeA = 0,
  TreeB = 1,
  Bush = 2,
  Rock = 3,
  HayBale = 4,
  Pond = 5,
  Tent = 6,
  SpectatorA = 7,
  SpectatorB = 8,
  Windsock = 9,
}

export interface SpriteSheet {
  image: CanvasImageSource;
  /** Frame width/height in source pixels. */
  fw: number;
  fh: number;
  frames: number;
}

export type SpriteAtlas = Record<SheetName, SpriteSheet>;

/** Load every sheet; resolves once all images are decoded. */
export async function loadAtlas(basePath = 'assets/sprites'): Promise<SpriteAtlas> {
  const entries = await Promise.all(
    (Object.keys(SHEET_SPECS) as SheetName[]).map(async (name) => {
      const spec = SHEET_SPECS[name];
      const image = new Image();
      image.src = `${basePath}/${name}.png`;
      await image.decode();
      return [name, { image, ...spec }] as const;
    }),
  );
  return Object.fromEntries(entries) as SpriteAtlas;
}

/**
 * Draw one frame centred on (x, y), scaled by `scale` (1 = native pixels) and
 * optionally rotated. Coordinates are snapped to whole pixels so nearest-
 * neighbour sampling stays crisp.
 */
export function drawSprite(
  ctx: CanvasRenderingContext2D,
  sheet: SpriteSheet,
  frame: number,
  x: number,
  y: number,
  scale = 1,
  rotation = 0,
): void {
  const f = Math.min(sheet.frames - 1, Math.max(0, Math.round(frame)));
  const dw = Math.max(1, Math.round(sheet.fw * scale));
  const dh = Math.max(1, Math.round(sheet.fh * scale));
  if (rotation !== 0) {
    ctx.save();
    ctx.translate(Math.round(x), Math.round(y));
    ctx.rotate(rotation);
    ctx.drawImage(sheet.image, f * sheet.fw, 0, sheet.fw, sheet.fh, -dw / 2, -dh / 2, dw, dh);
    ctx.restore();
  } else {
    ctx.drawImage(
      sheet.image,
      f * sheet.fw,
      0,
      sheet.fw,
      sheet.fh,
      Math.round(x - dw / 2),
      Math.round(y - dh / 2),
      dw,
      dh,
    );
  }
}
